console.log("[Start]");

try {
  foo();
} catch (error) {
  console.error("[에러 발생]", error);
}

console.log("[End]");
